import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// 🔤 Hindi Unicode Font
import NotoDeva from '../assets/fonts/NotoSansDevanagari-Regular.ttf';

export class PDFGenerator {

  static generatePDFFromLessonPlans(
    className: string,
    section: string,
    weekRange: string,
    generatedBy: string,
    lessonPlans: any[],
    teachers: any[]
  ): string {

    const doc = new jsPDF('p', 'mm', 'a4');

    /* ================= FONT SETUP (MOST IMPORTANT) ================= */
    doc.addFileToVFS('NotoDeva.ttf', NotoDeva);
    doc.addFont('NotoDeva.ttf', 'NotoDeva', 'normal');
    doc.setFont('NotoDeva');

    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 15;

    /* ================= HEADER ================= */
    doc.setFontSize(14);
    doc.text('SACRED HEART SCHOOL', pageWidth / 2, y, { align: 'center' });

    y += 6;
    doc.setFontSize(10);
    doc.text('सैक्रेड हार्ट स्कूल', pageWidth / 2, y, { align: 'center' });

    y += 5;
    doc.setFontSize(9);
    doc.text('(Affiliated to CBSE, New Delhi, upto +2 Level)', pageWidth / 2, y, { align: 'center' });

    y += 8;
    doc.setFontSize(12);
    doc.text('WEEKLY SYLLABUS', pageWidth / 2, y, { align: 'center' });

    y += 6;
    doc.setFontSize(10);
    doc.text('साप्ताहिक पाठ्यक्रम', pageWidth / 2, y, { align: 'center' });

    y += 10;
    doc.setFontSize(9);
    doc.text(`Date: ${weekRange}`, 14, y);

    y += 6;
    doc.text(`Class & Section: ${className} - ${section}`, 14, y);

    y += 6;
    doc.text(`Class Teacher: ${generatedBy}`, 14, y);

    /* ================= TABLE DATA ================= */
    const tableBody = teachers.map(t => {
      const plan = lessonPlans.find(
        p =>
          p.teacherId === t.email &&
          p.className === className &&
          p.section === section &&
          p.weekRange === weekRange
      );

      return [
        t.subject || '—',
        t.name || '—',
        plan ? plan.topics?.split('\n')[0] || '—' : '---',
        plan ? 'Submitted' : 'Homework Not Submitted',
        plan ? '' : 'गृहकार्य जमा नहीं हुआ'
      ];
    });

    /* ================= TABLE ================= */
    autoTable(doc, {
      startY: y + 6,
      head: [[
        'Subject',
        'Teacher',
        'Chapter',
        'Status',
        'स्थिति'
      ]],
      body: tableBody,
      styles: {
        font: 'NotoDeva',
        fontSize: 9,
        cellPadding: 2
      },
      headStyles: {
        font: 'NotoDeva',
        fillColor: [230, 230, 230],
        textColor: 0
      }
    });

    /* ================= SUMMARY ================= */
    const submittedCount = tableBody.filter(r => r[3] === 'Submitted').length;
    const missingCount = tableBody.length - submittedCount;

    let summaryY = (doc as any).lastAutoTable.finalY + 10;

    doc.setFontSize(10);
    doc.text('Summary:', 14, summaryY);

    summaryY += 5;
    doc.text(`• Total Teachers: ${tableBody.length}`, 14, summaryY);

    summaryY += 5;
    doc.text(`• Submitted: ${submittedCount}`, 14, summaryY);

    summaryY += 5;
    doc.text(`• Missing: ${missingCount}`, 14, summaryY);

    summaryY += 8;
    doc.text('(Homework Not Submitted)', 14, summaryY);

    /* ================= SIGNATURES ================= */
    summaryY += 12;
    doc.text('Signature of Class Teacher:', 14, summaryY);

    summaryY += 5;
    doc.text('कक्षा अध्यापक के हस्ताक्षर:', 14, summaryY);

    summaryY += 10;
    doc.text('Signature of Principal:', 14, summaryY);

    summaryY += 5;
    doc.text('प्राचार्य के हस्ताक्षर:', 14, summaryY);

    /* ================= FOOTER ================= */
    doc.setFontSize(8);
    doc.text(
      `Generated by Sacred Heart School Management System • ${new Date().toLocaleDateString('en-IN')}`,
      pageWidth / 2,
      290,
      { align: 'center' }
    );

    /* ================= RETURN BASE64 ================= */
    return doc.output('datauristring').split(',')[1];
  }
}
