import jsPDF from 'jspdf';
import NotoDeva from '../assets/fonts/NotoSansDevanagari-Regular.ttf';

export class PDFGenerator {

  static generatePDFFromLessonPlans(
    className: string,
    section: string,
    weekRange: string,
    generatedBy: string,
    lessonPlans: any[],
    teachers: any[]
  ): string {

    const doc = new jsPDF('p', 'mm', 'a4');

    /* ================= FONT ================= */
    doc.addFileToVFS('NotoDeva.ttf', NotoDeva);
    doc.addFont('NotoDeva.ttf', 'NotoDeva', 'normal');
    doc.setFont('NotoDeva');

    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 15;

    /* ================= HEADER ================= */
    doc.setFontSize(14);
    doc.text('SACRED HEART SCHOOL', pageWidth / 2, y, { align: 'center' });

    y += 6;
    doc.setFontSize(10);
    doc.text('सैक्रेड हार्ट स्कूल', pageWidth / 2, y, { align: 'center' });

    y += 5;
    doc.setFontSize(9);
    doc.text('(Affiliated to CBSE, New Delhi, upto +2 Level)', pageWidth / 2, y, { align: 'center' });

    y += 8;
    doc.setFontSize(12);
    doc.text('WEEKLY SYLLABUS', pageWidth / 2, y, { align: 'center' });

    y += 6;
    doc.setFontSize(10);
    doc.text('साप्ताहिक पाठ्यक्रम', pageWidth / 2, y, { align: 'center' });

    y += 10;
    doc.setFontSize(9);
    doc.text(`Date: ${weekRange}`, 14, y);
    y += 6;
    doc.text(`Class & Section: ${className} - ${section}`, 14, y);
    y += 6;
    doc.text(`Class Teacher: ${generatedBy}`, 14, y);

    /* ================= TABLE HEADER ================= */
    y += 10;
    doc.setFontSize(9);

    const colX = [14, 45, 90, 135, 165];
    const rowHeight = 7;

    const drawRow = (values: string[]) => {
      values.forEach((v, i) => {
        doc.text(v, colX[i], y);
      });
      y += rowHeight;
    };

    drawRow(['Subject', 'Teacher', 'Chapter', 'Status', 'स्थिति']);
    y += 1;

    doc.line(14, y - 6, 196, y - 6);

    /* ================= TABLE BODY ================= */
    if (!teachers || teachers.length === 0) {
      drawRow(['—', '—', 'कोई डेटा उपलब्ध नहीं', '—', '—']);
    } else {
      teachers.forEach(t => {
        const plan = (lessonPlans || []).find(
          p =>
            p.teacherId === t.email &&
            p.className === className &&
            p.section === section &&
            p.weekRange === weekRange
        );

        drawRow([
          t.subject || '—',
          t.name || '—',
          plan ? plan.topics?.split('\n')[0] || '—' : '—',
          plan ? 'Submitted' : 'Homework Not Submitted',
          plan ? 'जमा हुआ' : 'गृहकार्य जमा नहीं हुआ'
        ]);

        if (y > 270) {
          doc.addPage();
          y = 20;
        }
      });
    }

    /* ================= SUMMARY ================= */
    y += 8;
    doc.setFontSize(10);
    doc.text('Summary:', 14, y);

    const submitted = (lessonPlans || []).filter(
      p => p.className === className && p.section === section && p.weekRange === weekRange
    ).length;

    y += 5;
    doc.text(`• Total Teachers: ${teachers?.length || 0}`, 14, y);
    y += 5;
    doc.text(`• Submitted: ${submitted}`, 14, y);
    y += 5;
    doc.text(`• Missing: ${(teachers?.length || 0) - submitted}`, 14, y);

    y += 8;
    doc.text('(Homework Not Submitted)', 14, y);

    /* ================= SIGNATURE ================= */
    y += 12;
    doc.text('Signature of Class Teacher:', 14, y);
    y += 5;
    doc.text('कक्षा अध्यापक के हस्ताक्षर:', 14, y);

    y += 10;
    doc.text('Signature of Principal:', 14, y);
    y += 5;
    doc.text('प्राचार्य के हस्ताक्षर:', 14, y);

    /* ================= FOOTER ================= */
    doc.setFontSize(8);
    doc.text(
      `Generated by Sacred Heart School Management System • ${new Date().toLocaleDateString('en-IN')}`,
      pageWidth / 2,
      290,
      { align: 'center' }
    );

    /* ================= RETURN ================= */
    return doc.output('datauristring').split(',')[1];
  }
}
